# Generated by Django 5.0.2 on 2024-03-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otpcode_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='555-555-5555', max_length=15),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='5afb4', max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='5555-555-555', max_length=15),
        ),
    ]
