# Generated by Django 5.0.2 on 2024-03-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_doctor_phone_alter_otpcode_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default='4c3dd', max_length=6),
        ),
    ]
